/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeTermsRouteImport } from './routes/$countryCode/terms'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeSkincareGuideRouteImport } from './routes/$countryCode/skincare-guide'
import { Route as CountryCodeShippingRouteImport } from './routes/$countryCode/shipping'
import { Route as CountryCodeReturnsRouteImport } from './routes/$countryCode/returns'
import { Route as CountryCodeQuizResultsRouteImport } from './routes/$countryCode/quiz-results'
import { Route as CountryCodeQuizRouteImport } from './routes/$countryCode/quiz'
import { Route as CountryCodePrivacyRouteImport } from './routes/$countryCode/privacy'
import { Route as CountryCodePaymentsRouteImport } from './routes/$countryCode/payments'
import { Route as CountryCodeOurStoryRouteImport } from './routes/$countryCode/our-story'
import { Route as CountryCodeFaqRouteImport } from './routes/$countryCode/faq'
import { Route as CountryCodeExperiencesRouteImport } from './routes/$countryCode/experiences'
import { Route as CountryCodeContactRouteImport } from './routes/$countryCode/contact'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeBlogRouteImport } from './routes/$countryCode/blog'
import { Route as CountryCodeAccountRouteImport } from './routes/$countryCode/account'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode/account/index'
import { Route as CountryCodeQuizConfirmRouteImport } from './routes/$countryCode/quiz/confirm'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeFormulationsProtectiveMoisturizerRouteImport } from './routes/$countryCode/formulations/protective-moisturizer'
import { Route as CountryCodeFormulationsHydratingMoisturizerRouteImport } from './routes/$countryCode/formulations/hydrating-moisturizer'
import { Route as CountryCodeFormulationsBalancingMoisturizerRouteImport } from './routes/$countryCode/formulations/balancing-moisturizer'
import { Route as CountryCodeCollectionsHandleRouteImport } from './routes/$countryCode/collections/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeAccountOrdersIndexRouteImport } from './routes/$countryCode/account/orders/index'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'
import { Route as CountryCodeAccountOrdersOrderIdRouteImport } from './routes/$countryCode/account/orders/$orderId'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTermsRoute = CountryCodeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSkincareGuideRoute =
  CountryCodeSkincareGuideRouteImport.update({
    id: '/skincare-guide',
    path: '/skincare-guide',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeShippingRoute = CountryCodeShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeReturnsRoute = CountryCodeReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuizResultsRoute = CountryCodeQuizResultsRouteImport.update({
  id: '/quiz-results',
  path: '/quiz-results',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuizRoute = CountryCodeQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePrivacyRoute = CountryCodePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePaymentsRoute = CountryCodePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeOurStoryRoute = CountryCodeOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeFaqRoute = CountryCodeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeExperiencesRoute = CountryCodeExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeContactRoute = CountryCodeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeBlogRoute = CountryCodeBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountRoute = CountryCodeAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeAccountRoute,
} as any)
const CountryCodeQuizConfirmRoute = CountryCodeQuizConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => CountryCodeQuizRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeFormulationsProtectiveMoisturizerRoute =
  CountryCodeFormulationsProtectiveMoisturizerRouteImport.update({
    id: '/formulations/protective-moisturizer',
    path: '/formulations/protective-moisturizer',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeFormulationsHydratingMoisturizerRoute =
  CountryCodeFormulationsHydratingMoisturizerRouteImport.update({
    id: '/formulations/hydrating-moisturizer',
    path: '/formulations/hydrating-moisturizer',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeFormulationsBalancingMoisturizerRoute =
  CountryCodeFormulationsBalancingMoisturizerRouteImport.update({
    id: '/formulations/balancing-moisturizer',
    path: '/formulations/balancing-moisturizer',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCollectionsHandleRoute =
  CountryCodeCollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersIndexRoute =
  CountryCodeAccountOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersOrderIdRoute =
  CountryCodeAccountOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/account': typeof CountryCodeAccountRouteWithChildren
  '/$countryCode/blog': typeof CountryCodeBlogRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/experiences': typeof CountryCodeExperiencesRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/our-story': typeof CountryCodeOurStoryRoute
  '/$countryCode/payments': typeof CountryCodePaymentsRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/quiz': typeof CountryCodeQuizRouteWithChildren
  '/$countryCode/quiz-results': typeof CountryCodeQuizResultsRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/shipping': typeof CountryCodeShippingRoute
  '/$countryCode/skincare-guide': typeof CountryCodeSkincareGuideRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/formulations/balancing-moisturizer': typeof CountryCodeFormulationsBalancingMoisturizerRoute
  '/$countryCode/formulations/hydrating-moisturizer': typeof CountryCodeFormulationsHydratingMoisturizerRoute
  '/$countryCode/formulations/protective-moisturizer': typeof CountryCodeFormulationsProtectiveMoisturizerRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quiz/confirm': typeof CountryCodeQuizConfirmRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders/': typeof CountryCodeAccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/blog': typeof CountryCodeBlogRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/experiences': typeof CountryCodeExperiencesRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/our-story': typeof CountryCodeOurStoryRoute
  '/$countryCode/payments': typeof CountryCodePaymentsRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/quiz': typeof CountryCodeQuizRouteWithChildren
  '/$countryCode/quiz-results': typeof CountryCodeQuizResultsRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/shipping': typeof CountryCodeShippingRoute
  '/$countryCode/skincare-guide': typeof CountryCodeSkincareGuideRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/formulations/balancing-moisturizer': typeof CountryCodeFormulationsBalancingMoisturizerRoute
  '/$countryCode/formulations/hydrating-moisturizer': typeof CountryCodeFormulationsHydratingMoisturizerRoute
  '/$countryCode/formulations/protective-moisturizer': typeof CountryCodeFormulationsProtectiveMoisturizerRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quiz/confirm': typeof CountryCodeQuizConfirmRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/account': typeof CountryCodeAccountRouteWithChildren
  '/$countryCode/blog': typeof CountryCodeBlogRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/experiences': typeof CountryCodeExperiencesRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/our-story': typeof CountryCodeOurStoryRoute
  '/$countryCode/payments': typeof CountryCodePaymentsRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/quiz': typeof CountryCodeQuizRouteWithChildren
  '/$countryCode/quiz-results': typeof CountryCodeQuizResultsRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/shipping': typeof CountryCodeShippingRoute
  '/$countryCode/skincare-guide': typeof CountryCodeSkincareGuideRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/collections/$handle': typeof CountryCodeCollectionsHandleRoute
  '/$countryCode/formulations/balancing-moisturizer': typeof CountryCodeFormulationsBalancingMoisturizerRoute
  '/$countryCode/formulations/hydrating-moisturizer': typeof CountryCodeFormulationsHydratingMoisturizerRoute
  '/$countryCode/formulations/protective-moisturizer': typeof CountryCodeFormulationsProtectiveMoisturizerRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quiz/confirm': typeof CountryCodeQuizConfirmRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders/': typeof CountryCodeAccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/account'
    | '/$countryCode/blog'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/experiences'
    | '/$countryCode/faq'
    | '/$countryCode/our-story'
    | '/$countryCode/payments'
    | '/$countryCode/privacy'
    | '/$countryCode/quiz'
    | '/$countryCode/quiz-results'
    | '/$countryCode/returns'
    | '/$countryCode/shipping'
    | '/$countryCode/skincare-guide'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/formulations/balancing-moisturizer'
    | '/$countryCode/formulations/hydrating-moisturizer'
    | '/$countryCode/formulations/protective-moisturizer'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quiz/confirm'
    | '/$countryCode/account/'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/blog'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/experiences'
    | '/$countryCode/faq'
    | '/$countryCode/our-story'
    | '/$countryCode/payments'
    | '/$countryCode/privacy'
    | '/$countryCode/quiz'
    | '/$countryCode/quiz-results'
    | '/$countryCode/returns'
    | '/$countryCode/shipping'
    | '/$countryCode/skincare-guide'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/formulations/balancing-moisturizer'
    | '/$countryCode/formulations/hydrating-moisturizer'
    | '/$countryCode/formulations/protective-moisturizer'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quiz/confirm'
    | '/$countryCode/account'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/account'
    | '/$countryCode/blog'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/experiences'
    | '/$countryCode/faq'
    | '/$countryCode/our-story'
    | '/$countryCode/payments'
    | '/$countryCode/privacy'
    | '/$countryCode/quiz'
    | '/$countryCode/quiz-results'
    | '/$countryCode/returns'
    | '/$countryCode/shipping'
    | '/$countryCode/skincare-guide'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/formulations/balancing-moisturizer'
    | '/$countryCode/formulations/hydrating-moisturizer'
    | '/$countryCode/formulations/protective-moisturizer'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quiz/confirm'
    | '/$countryCode/account/'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HealthRoute: typeof HealthRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/terms': {
      id: '/$countryCode/terms'
      path: '/terms'
      fullPath: '/$countryCode/terms'
      preLoaderRoute: typeof CountryCodeTermsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/skincare-guide': {
      id: '/$countryCode/skincare-guide'
      path: '/skincare-guide'
      fullPath: '/$countryCode/skincare-guide'
      preLoaderRoute: typeof CountryCodeSkincareGuideRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/shipping': {
      id: '/$countryCode/shipping'
      path: '/shipping'
      fullPath: '/$countryCode/shipping'
      preLoaderRoute: typeof CountryCodeShippingRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/returns': {
      id: '/$countryCode/returns'
      path: '/returns'
      fullPath: '/$countryCode/returns'
      preLoaderRoute: typeof CountryCodeReturnsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quiz-results': {
      id: '/$countryCode/quiz-results'
      path: '/quiz-results'
      fullPath: '/$countryCode/quiz-results'
      preLoaderRoute: typeof CountryCodeQuizResultsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quiz': {
      id: '/$countryCode/quiz'
      path: '/quiz'
      fullPath: '/$countryCode/quiz'
      preLoaderRoute: typeof CountryCodeQuizRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/privacy': {
      id: '/$countryCode/privacy'
      path: '/privacy'
      fullPath: '/$countryCode/privacy'
      preLoaderRoute: typeof CountryCodePrivacyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/payments': {
      id: '/$countryCode/payments'
      path: '/payments'
      fullPath: '/$countryCode/payments'
      preLoaderRoute: typeof CountryCodePaymentsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/our-story': {
      id: '/$countryCode/our-story'
      path: '/our-story'
      fullPath: '/$countryCode/our-story'
      preLoaderRoute: typeof CountryCodeOurStoryRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/faq': {
      id: '/$countryCode/faq'
      path: '/faq'
      fullPath: '/$countryCode/faq'
      preLoaderRoute: typeof CountryCodeFaqRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/experiences': {
      id: '/$countryCode/experiences'
      path: '/experiences'
      fullPath: '/$countryCode/experiences'
      preLoaderRoute: typeof CountryCodeExperiencesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/contact': {
      id: '/$countryCode/contact'
      path: '/contact'
      fullPath: '/$countryCode/contact'
      preLoaderRoute: typeof CountryCodeContactRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/blog': {
      id: '/$countryCode/blog'
      path: '/blog'
      fullPath: '/$countryCode/blog'
      preLoaderRoute: typeof CountryCodeBlogRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account': {
      id: '/$countryCode/account'
      path: '/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeAccountRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/quiz/confirm': {
      id: '/$countryCode/quiz/confirm'
      path: '/confirm'
      fullPath: '/$countryCode/quiz/confirm'
      preLoaderRoute: typeof CountryCodeQuizConfirmRouteImport
      parentRoute: typeof CountryCodeQuizRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/formulations/protective-moisturizer': {
      id: '/$countryCode/formulations/protective-moisturizer'
      path: '/formulations/protective-moisturizer'
      fullPath: '/$countryCode/formulations/protective-moisturizer'
      preLoaderRoute: typeof CountryCodeFormulationsProtectiveMoisturizerRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/formulations/hydrating-moisturizer': {
      id: '/$countryCode/formulations/hydrating-moisturizer'
      path: '/formulations/hydrating-moisturizer'
      fullPath: '/$countryCode/formulations/hydrating-moisturizer'
      preLoaderRoute: typeof CountryCodeFormulationsHydratingMoisturizerRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/formulations/balancing-moisturizer': {
      id: '/$countryCode/formulations/balancing-moisturizer'
      path: '/formulations/balancing-moisturizer'
      fullPath: '/$countryCode/formulations/balancing-moisturizer'
      preLoaderRoute: typeof CountryCodeFormulationsBalancingMoisturizerRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/collections/$handle': {
      id: '/$countryCode/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/$countryCode/collections/$handle'
      preLoaderRoute: typeof CountryCodeCollectionsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders/': {
      id: '/$countryCode/account/orders/'
      path: '/orders'
      fullPath: '/$countryCode/account/orders/'
      preLoaderRoute: typeof CountryCodeAccountOrdersIndexRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders/$orderId': {
      id: '/$countryCode/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$countryCode/account/orders/$orderId'
      preLoaderRoute: typeof CountryCodeAccountOrdersOrderIdRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
  }
}

interface CountryCodeAccountRouteChildren {
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeAccountOrdersOrderIdRoute: typeof CountryCodeAccountOrdersOrderIdRoute
  CountryCodeAccountOrdersIndexRoute: typeof CountryCodeAccountOrdersIndexRoute
}

const CountryCodeAccountRouteChildren: CountryCodeAccountRouteChildren = {
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeAccountOrdersOrderIdRoute: CountryCodeAccountOrdersOrderIdRoute,
  CountryCodeAccountOrdersIndexRoute: CountryCodeAccountOrdersIndexRoute,
}

const CountryCodeAccountRouteWithChildren =
  CountryCodeAccountRoute._addFileChildren(CountryCodeAccountRouteChildren)

interface CountryCodeQuizRouteChildren {
  CountryCodeQuizConfirmRoute: typeof CountryCodeQuizConfirmRoute
}

const CountryCodeQuizRouteChildren: CountryCodeQuizRouteChildren = {
  CountryCodeQuizConfirmRoute: CountryCodeQuizConfirmRoute,
}

const CountryCodeQuizRouteWithChildren = CountryCodeQuizRoute._addFileChildren(
  CountryCodeQuizRouteChildren,
)

interface CountryCodeRouteChildren {
  CountryCodeAccountRoute: typeof CountryCodeAccountRouteWithChildren
  CountryCodeBlogRoute: typeof CountryCodeBlogRoute
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeContactRoute: typeof CountryCodeContactRoute
  CountryCodeExperiencesRoute: typeof CountryCodeExperiencesRoute
  CountryCodeFaqRoute: typeof CountryCodeFaqRoute
  CountryCodeOurStoryRoute: typeof CountryCodeOurStoryRoute
  CountryCodePaymentsRoute: typeof CountryCodePaymentsRoute
  CountryCodePrivacyRoute: typeof CountryCodePrivacyRoute
  CountryCodeQuizRoute: typeof CountryCodeQuizRouteWithChildren
  CountryCodeQuizResultsRoute: typeof CountryCodeQuizResultsRoute
  CountryCodeReturnsRoute: typeof CountryCodeReturnsRoute
  CountryCodeShippingRoute: typeof CountryCodeShippingRoute
  CountryCodeSkincareGuideRoute: typeof CountryCodeSkincareGuideRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeTermsRoute: typeof CountryCodeTermsRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeCollectionsHandleRoute: typeof CountryCodeCollectionsHandleRoute
  CountryCodeFormulationsBalancingMoisturizerRoute: typeof CountryCodeFormulationsBalancingMoisturizerRoute
  CountryCodeFormulationsHydratingMoisturizerRoute: typeof CountryCodeFormulationsHydratingMoisturizerRoute
  CountryCodeFormulationsProtectiveMoisturizerRoute: typeof CountryCodeFormulationsProtectiveMoisturizerRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeAccountRoute: CountryCodeAccountRouteWithChildren,
  CountryCodeBlogRoute: CountryCodeBlogRoute,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeContactRoute: CountryCodeContactRoute,
  CountryCodeExperiencesRoute: CountryCodeExperiencesRoute,
  CountryCodeFaqRoute: CountryCodeFaqRoute,
  CountryCodeOurStoryRoute: CountryCodeOurStoryRoute,
  CountryCodePaymentsRoute: CountryCodePaymentsRoute,
  CountryCodePrivacyRoute: CountryCodePrivacyRoute,
  CountryCodeQuizRoute: CountryCodeQuizRouteWithChildren,
  CountryCodeQuizResultsRoute: CountryCodeQuizResultsRoute,
  CountryCodeReturnsRoute: CountryCodeReturnsRoute,
  CountryCodeShippingRoute: CountryCodeShippingRoute,
  CountryCodeSkincareGuideRoute: CountryCodeSkincareGuideRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeTermsRoute: CountryCodeTermsRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeCollectionsHandleRoute: CountryCodeCollectionsHandleRoute,
  CountryCodeFormulationsBalancingMoisturizerRoute:
    CountryCodeFormulationsBalancingMoisturizerRoute,
  CountryCodeFormulationsHydratingMoisturizerRoute:
    CountryCodeFormulationsHydratingMoisturizerRoute,
  CountryCodeFormulationsProtectiveMoisturizerRoute:
    CountryCodeFormulationsProtectiveMoisturizerRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HealthRoute: HealthRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
